export const CONNECTING_TO_SERVER = 'actions/CONNECTING_TO_SERVER'
export const CONNECTING_TO_SERVER_COMPLETE = 'actions/CONNECTING_TO_SERVER_COMPLETE'

export const UPDATE_EDITOR = 'actions/UPDATE_EDITOR'
