export const CONNECTING_TO_SERVER = 'actions/CONNECTING_TO_SERVER'
export const CONNECTING_TO_SERVER_COMPLETE = 'actions/CONNECTING_TO_SERVER_COMPLETE'

export const UPDATE_EDITOR = 'actions/UPDATE_EDITOR'

export const EVALUATING_CODE = 'actions/EVALUATING_CODE'
export const EVALUATING_CODE_COMPLETE = 'actions/EVALUATING_CODE_COMPLETE'

export const SET_USER = 'actions/SET_USER'
